[window]
opacity = 0.95
resize_increments = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 13
offset = { x = 0, y = 0 }

[colors.primary]
background = "#101019"

[mouse]
hide_when_typing = true
