[window]
opacity = 0.8
resize_increments = true

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 14
offset = { x = 0, y = 1 }

[mouse]
hide_when_typing = true

# Dracula theme
[colors.primary]
# background = "0x282a36"
background = "#1e1e2e"
foreground = "0xf8f8f2"

[colors.normal]
black = "0x000000"
red = "0xff5555"
green = "0x50fa7b"
yellow = "0xf1fa8c"
blue = "0xbd93f9"
magenta = "0xff79c6"
cyan = "0x8be9fd"
white = "0xbbbbbb"

[colors.bright]
black = "0x555555"
red = "0xff5555"
green = "0x50fa7b"
yellow = "0xf1fa8c"
blue = "0xcaa9fa"
magenta = "0xff79c6"
cyan = "0x8be9fd"
white = "0xffffff"
