[window]
opacity = 0.9
resize_increments = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 11

[colors.primary]
background = "#101019"

[mouse]
hide_when_typing = true
