return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"css",
			"diff",
			"dockerfile",
			"gitignore",
			"go",
			"java",
			"javascript",
			"jsdoc",
			"html",
			"lua",
			"php",
			"phpdoc",
			"make",
			"markdown",
			"markdown_inline",
			"ocaml",
			"python",
			"query",
			"rust",
			"sql",
			"terraform",
			"tsx",
			"twig",
			"typescript",
			"vim",
			"vimdoc",
			"vue",
			"yaml",
		},
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = { "ruby" },
		},
		indent = {
			enable = true,
			disable = { "ruby" },
		},
	},
}
