#alias npm='docker run -it --name npm --rm -v $PWD:/app -w /app -e HOME=/app -p 3000:3000 node:14 npm'
#alias npm-lts='docker run -it --name npm --rm -v $PWD:/app -w /app -e HOME=/app -p 3000:3000 node:lts npm'
#alias npx='docker run -it --name npx --rm -v $PWD:/app -w /app -e HOME=/app node:15 npx'
#alias npx-lts='docker run -it --rm -v $PWD:/app -w /app -e HOME=/app -p 8545:8545 node:lts npx'
#alias node='docker run -it --rm -v $PWD:/app -w /app -e HOME=/app -p 8545:8545 node:latest node'
#alias node-lts='docker run -it --rm -v $PWD:/app -w /app -e HOME=/app -p 8545:8545 node:lts node'
#alias yarn='docker run -it --name yarn --rm -v $PWD:/app -w /app -e HOME=/app -p 1337:1337 node:15 yarn'
#alias yarn='docker run -it --name yarn --rm -v $PWD:/app -w /app -e HOME=/app -p 1337:1337 node:15 yarn'
#alias yarn='docker run -it --name yarn --rm -v $PWD:/app -w /app -e HOME=/app -p 1337:1337 node:lts yarn'
#alias composer='docker run -it --name composer --rm -v $PWD:/app -w /app -e HOME=/app composer composer'
#alias php='docker run --name php --rm -v $PWD:/var/www -p 8080:8080 -w /var/www php:8-alpine php'
alias composer1='docker run -it --name composer --rm -v $PWD:/app -w /app -e HOME=/app composer composer'
alias terraform='docker run --rm -it -v $HOME/.ssh:/root/.ssh -v $HOME/.aws:/root/.aws -v $PWD:/var/www -w /var/www hashicorp/terraform:latest'
alias eth='docker run -it --rm -v $PWD:/share trailofbits/eth-security-toolbox'
alias bettercap='sudo docker run --rm -it --privileged --net=host -p 80:80 -p 8081:8081  bettercap/bettercap bettercap'
alias mysql='docker run --rm -it --privileged --net=host -v $PWD:/var/www -w /var/www mysql mysql'
alias ds='docker-compose'
alias v='vim .'
alias dit='docker exec -it'
alias ditu='docker exec -itu root'
alias djf='cd ~/Projects/jfmelo/dotfiles && vim .'

